### ISSUE TITLE
Create API for Photos

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/HabboAPI#3]
It's possible to extract a Habbos photos via the 'extradata' endpoint.

**Comment by DavydeVries** [comment]
I like to help, with photos and stories from habbos.
- Stories
  - powertoo (hhus-ea4890c42ddf7ed57ed38bda6cd21e70) has stories.
  - request url: https://www.habbo.com/extradata/public/users/{hhus-xxx}/stories
- Photos
  - bamboo (hhus-31fd847f4f3f3ee3e3257ca0bd66a60b) has photos.
  - request url: https://www.habbo.com/extradata/public/users/{hhus-xxx}/photos
  - public/random photo stream: https://www.habbo.com/extradata/public/photos
- Other request urls
  - (auth needed) https://www.habbo.com/shopapi/purse (receive balance like credits, diamonds, hc, etc.) 
  - http://habboo-a.akamaihd.net/dcr/hof_furni/{revision}/{swf_classname}_icon.png (Furni icon images)
  - (auth needed) https://www.habbo.com/api/user/discussions (receive private messages)
  - (auth needed) https://www.habbo.com/api/user/preferences (personal settings, possibly with a POST request editable)
  - (auth needed) https://www.habbo.com/api/user/campaign_messages (no idea...)
  - (auth needed) https://www.habbo.com/extradata/private/moderations/recentModerations (no idea...)

**Comment by gerbenjacobs** [comment]
Nice ideas. I think we can go through with the Photos.
However for the Stories part (which is only in COM/BR/ES) I heard that it might get cancelled. In Habbo.com all remnants are gone, except for on the profiles.

For all the Auth based endpoints; I'm not sure if this is a good idea considering who is the prime enduser of this library (i.e. fansites)
They don't have a good track record of being secure and I don't like the idea of making it easier for them to lose private data (which you'll need to make the auth urls work). If you want you can create a new issue for it to see if it gets traction.

**Comment by DavydeVries** [comment]
- Stories
  - I didn't know that might be dropped by Habbo/Sulake. (Maybe wait until we figure out what Habbo is going to do)
- Auth based endpoints
  - You are right about that. You need a password for authentication, which is against the Habbo(way) rules.
  - _"If you want you can create a new issue for it to see if it gets traction."_ I guess we'll just have to wait until Habbo going to use API keys. Especially for this issue.
- Parser url
  - About the parser url because /extradata/public/ is different we need to figure out how we going to handle that.

_(Btw do you prefer to communicate further on github in English?)_

**Comment by gerbenjacobs** [comment]
I was editing `example.php` to include Photos and I found out that anything on /extradata/ requires some silly cookie. A bit surprised because I literally thought I was ready with the Photos feature. (Apart from the fact I also forgot to add getPhotos() to the API)
