### ISSUE TITLE
Calling /members of big groups always returns {"error":"maintenance"}

### ISSUE THREAD

**Issue by Pandafuchs** [gerbenjacobs/HabboAPI#41]
1. Call https://www.habbo.de/api/public/groups/g-hhde-9b007fb914a7f22e15ddd7e1825a728d/members
2. See the result: {"error":"maintenance"}
3. Call https://www.habbo.de/api/public/groups/g-hhde-9b007fb914a7f22e15ddd7e1825a728d
4. That works, no maintenance. 

I think with over 30k members the group is just too big. Is there a workaround?

**Comment by gerbenjacobs** [comment]
It could be a number, but I also remember that it could be because of the '[type](http://habbo.wikia.com/wiki/Groups#Group_Settings)' of group. If the group is **Unlimited** I guess it makes no sense for Habbo to show them as it could be massive.

Unfortunately there is no workaround. If Habbo doesn't give it, we can't.
In fact it's even worse that they say `error: maintenance` because we can't distinguish between an 'Unlimited group' or the hotel actually being down..

**Comment by Pandafuchs** [comment]
Okay so Habbo just sucks. Good to know. Maybe someday we'll get a better API. HAHAHA just kidding, we never will :D

**Comment by Pandafuchs** [comment]
Apparently the behaviour changed. You now get
"Cannot GET /api/public/groups/g-hhde-9b007fb914a7f22e15ddd7e1825a728d/members"
all the time, regardless of the group size.

**Comment by gerbenjacobs** [comment]
Yeah, I saw that yesterday when I was checking issues. That's too bad :(

**Comment by Pandafuchs** [comment]
Now the only way to do it would be to use inofficial APIs like this one
https://hh-crawler.tk/ords/habbo/api/group/g-hhde-bd972ee15b4175bd6379d0659ac02541/members
